---

- name: Install Confluent public key
  apt_key: url="http://packages.confluent.io/deb/{{ confluent_platform_repo_version }}/archive.key" state="present"

- name: Install Confluent repository
  apt_repository: repo="deb [arch=amd64] http://packages.confluent.io/deb/{{ confluent_platform_repo_version }} stable main"

- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install OpenJDK {{ openjdk_java_version }} Java
  apt: name=openjdk-{{ openjdk_java_version }}-jdk state=latest

- name: Install Confluent platform
  apt: "name=confluent-platform-oss-2.11={{ confluent_platform_package_version }} state=present"

- name: Install packages for pip
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - build-essential
  - libssl-dev
  - libffi-dev
  - python-dev
  - python-crypto

- name: Get pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /root

- name: Install pip
  shell: python /root/get-pip.py

- name: Install pyopenssl
  pip:
    name: pyopenssl
    version: 16.2.0

- name: Install kafka-utils
  pip:
    name: kafka-utils

- name: Install kafkacat
  apt: name=kafkacat state=latest
