---

- name: Add Oracle Java PPA repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Install Confluent repository
  apt_repository: repo="deb [arch=amd64] http://packages.confluent.io/deb/{{ confluent_platform_repo_version }} stable main"

- name: Install Confluent public key
  apt_key: url="http://packages.confluent.io/deb/3.3/archive.key" state="present"

- name: Accept Oracle license (1/2)
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections"

- name: Accept Oracle license (2/2)
  shell: "echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections"

- name: Update APT cache
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install Oracle Java
  apt: name=oracle-java8-installer state=latest

- name: Install Confluent platform
  apt: "name=confluent-platform-oss-2.11={{ confluent_platform_package_version }} state=present"

- name: Install packages for pip
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - build-essential
  - libssl-dev
  - libffi-dev
  - python-dev
  - python-crypto

- name: get pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /root

- name: Install pip
  shell: python /root/get-pip.py

- pip:
    name: pyopenssl
    version: 16.2.0

- pip:
    name: kafka-utils

- name: Install kafkacat
  apt: name=kafkacat state=latest
